name: test.sh
on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths: ['**.sh']
  push:
    branches: ['main']
    paths: ['**.sh']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: ./test/test.sh
